# Generated by Django 4.0.2 on 2022-03-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventspotapp', '0004_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='timestamp',
        ),
    ]
