# Generated by Django 4.0.2 on 2022-03-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventspotapp', '0007_event_lattitude_event_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
