# Generated by Django 4.0.2 on 2022-03-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventspotapp', '0018_event_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
