# Generated by Django 4.0.2 on 2022-03-23 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventspotapp', '0003_profile'),
        ('eventspotapp', '0019_alter_event_image'),
    ]

    operations = [
    ]
