# Generated by Django 4.0.2 on 2022-03-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventspotapp', '0020_merge_0003_profile_0019_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
