# Generated by Django 4.0.2 on 2022-03-29 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventspotapp', '0005_remove_friendrequest_is_active_and_more'),
        ('eventspotapp', '0021_alter_profile_profile_image'),
    ]

    operations = [
    ]
