# Generated by Django 4.0.2 on 2022-04-08 18:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eventspotapp', '0022_merge_20220329_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 18, 21, 8, 556552, tzinfo=utc)),
        ),
    ]
