# Generated by Django 4.0.2 on 2022-04-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventspotapp', '0023_rename_date_event_start_date_event_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
